version: '3.8'

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodekeylog-server
    restart: always
    volumes:
      - /root/keylog.txt:/root/keylog.txt
    expose:
      - "3000"

  nginx:
    image: nginx:alpine
    container_name: nodekeylog-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - node
